### ISSUE TITLE
sendMail example request is confusing (perhaps incorrect)

### ISSUE THREAD

**Issue by unpluggedk** [OfficeDev/microsoft-graph-docs#100]
The example request seems to indicate that there is already an attachment to the message by having the following within the request body.

   "attachments": [
      {
        "lastModifiedDateTime": "datetime-value",
        "name": "name-value",
        "contentType": "contentType-value",
        "size": 99,
        "isInline": true,
        "id": "id-value"
      }

However, per document, attachment is only possible to an existing message with the following APIs :
POST /me/messages/<id>/attachments
POST /users/<id | userPrincipalName>/messages/<id>/attachments

**Comment by unpluggedk** [comment]
It is also missing 
"@odata.type": "#Microsoft.OutlookServices.FileAttachment",

and doesn't specify what is required and what is optional.

**Comment by unpluggedk** [comment]
just a note with contentBytes,
"lastModifiedDateTime", "contentType", "size", "id" is not needed.

**Comment by martellaj** [comment]
@angelgolfer-ms, you're more familiar with the Outlook API. Can you please take a look at this sample request/response when you get a chance? Thanks!

**Comment by angelgolfer-ms** [comment]
@unpluggedk , thank you for your patience. I am checking with the product team about this issue. I'll post back after verifying.

**Comment by angelgolfer-ms** [comment]
@unpluggedk , sorry this took a while. I verified that sendmail does support including a file attachment. I clarified the support in the related content.
