### ISSUE TITLE
App-Only Mail Subscriptions

### ISSUE THREAD

**Issue by gregorydrake** [OfficeDev/microsoft-graph-docs#108]
The documentation on this has been scarce, but is Graph capable of handling an app-only subscription request?

Currently, I am working on a daemon for grabbing inbound and outbound mail from Office 365, but was unsure if the new Graph api could handle performing app-only subs, or if I needed to stick with Outlook's API's notification system for now.

**Comment by garethj-msft** [comment]
As of Jan 16, the subscriptions preview doesn't handle AppOnly.  We're currently working on when we'll have it available, but for now, you'd need to use the underlying Outlook notifications until we do.

**Comment by gregorydrake** [comment]
Okay!  Thanks for responding. I'm looking forward to seeing this potential feature in the future.

On Jan 22, 2016, at 5:31 PM, Joe Martella <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #108<https://github.com/OfficeDev/microsoft-graph-docs/issues/108>.
