### ISSUE TITLE
Start and End response objects.

### ISSUE THREAD

**Issue by IcyCaster** [OfficeDev/microsoft-graph-docs#116]
Is "Prefer | outlook.timezone="Pacific/Auckland" not working for creating a calendar event?

The response object I get back is always in UTC time for the Start and End DateTimeTimeZones, even though I specified "Pacific/Auckland".

Is this a bug or is it yet to be implemented...?

**Comment by angelgolfer-ms** [comment]
Hi @IcyCaster, the Prefer: outlook.timezone header is for only GET, not POST. When you are creating an event, set the time zone in the Start and End properties which are of the DateTimeTimeZone type. 
I clarified in the topic about this. Thanks for bringing this up! Close #116.

**Comment by IcyCaster** [comment]
Hi @angelgolfer-ms ,
I forgot to mention that I also included timezone in the Start and End properties as well.

### For example my POST request contains:

Start = new DateTimeTimeZone
                {
                    DateTime = DateTime.Now,
                    TimeZone = "Pacific/Auckland"
                }


### The model sent has values:
9/02/2016 **4**:00:00 **PM**
Pacific/Auckland

### However, the response model values are:
9/02/2016 **3**:00:00 **AM**
**UTC**


Is there any way for the response object to have the Start and End in the TimeZone I specified?

I need to make post-request checks, and dynamically converting from UTC to the specific timezone is possible but isn't ideal.

**Comment by angelgolfer-ms** [comment]
@IcyCaster , the Start and End values in the response should represent time in the Pacific/Auckland time zone. I just tried it on the v1.0 endpoint myself, please see attached Fiddler data, if that would help?
[Github_116_POST event time zone UTC.txt](https://github.com/OfficeDev/microsoft-graph-docs/files/123983/Github_116_POST.event.time.zone.UTC.txt)
