### ISSUE TITLE
POST request to group/threads/posts

### ISSUE THREAD

**Issue by dang2906** [OfficeDev/microsoft-graph-docs#120]
Hi When executing a post request as follows in order to create a new post in a thread:
https://graph.microsoft.com/beta/tenantid/groups/groupid/threads/threadid/posts

with the following body:
{
  "body": {
    "contentType": "html",
    "content": "This is a test"
  }
}

I am getting a 405 error

    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",

Is this an issue or have i implemented something wrong?

I am doing this through fiddler. I have also attempted using other HTTP methods such as put which reply with the same error message.

Any ideas?

**Comment by angelgolfer-ms** [comment]
@dang2906, I'll verify with the product team. Meanwhile, would you mind trying "reply": http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/post_reply

**Comment by dang2906** [comment]
Thanks for your response. I will go ahead and use post reply in the meantime. Also it would be good to have filtering available on 'topic' for thread rather than just on 'islocked'. Many Thanks :)

**Comment by angelgolfer-ms** [comment]
@dang2906 , FYI, I got confirmation that you cannot create a post as currently documented in http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/conversationthread_post_posts ( POST /threads/{id}/posts). Sorry for the confusion. I have already requested the topic to be removed from the TOC on the graph.microsoft.io site. I also clarified in the post resource topics the different ways that a post can be created. 

I'll call out your request for filtering on the "topic" property with the product team.

Thank you for your patience.

**Comment by dang2906** [comment]
Thats great thanks :) i believe the topic filtering would be a great feature if it is possible. Also i have just inspected the documentation, and although Create Post has been removed from [http://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/post](url) it is still visible on the navigation bar on the left hand side. Thanks for your help :)

**Comment by angelgolfer-ms** [comment]
Hi @dang2906 , you're very welcome! Yes, removing the item in the navigation bar is coming up. And meanwhile please bear with us while we work on streamlining the content update process :-)
