### ISSUE TITLE
GET /me/calendarGroup no longer works

### ISSUE THREAD

**Issue by Siern** [OfficeDev/microsoft-graph-docs#124]
The call to get the default group suddenly began failing for me this week.
I have reproduced it using your Microsoft Graph Explorer.  So short of an account specific issue, I believe this API call is now broken.

test example:
https://graph.microsoft.com/v1.0/me/calendarGroup

response:
```
 {
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type.",
        "innerError": {
            "request-id": "3a540d2b-f629-49e5-a9d8-0aaada641155",
            "date": "2016-02-18T14:58:40"
        }
    }
}
```

**Comment by sriram-d** [comment]
The name of the navigation property is calendarGroups and not calendarGroup (Refer to metadata at https://graph.microsoft.com/v1.0/$metadata or documentation at http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list_calendargroups). Please try the request as https://graph.microsoft.com/v1.0/me/calendarGroups.

**Comment by Siern** [comment]
While you are right it is no longer in the metadata.
But it seems to have been recently removed.
See documentation:
https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/calendargroup_get

> A user's default calendarGroup.
> 
> GET /me/calendarGroup
> GET /users/<id | userPrincipalName>/calendarGroup

As this is not the beta, it should not be subject to these types of changes!

Please note that the calendarGroup and calendarGroups are not the same.  The first was the default entity and the second is a collection of entities.

**Comment by marych** [comment]
As a note - calendarGroup has never been in v1.0 metadata. You're right that we should never remove anything from /v1.0 and we're very careful not to introduce any breaking changes to v1.0. This was a documentation issue only.

**Comment by angelgolfer-ms** [comment]
Re-read my last check-in note, want to qualify "there isn't a concept of default calendar group _with respect to this API_" - the API in question do not differentiate the default calendar group from other calendar groups and you reference any of them the same way by indexing into the calendar groups collection.
