### ISSUE TITLE
OrderBy DESC is ignored on users.displayName

### ISSUE THREAD

**Issue by MiroJanosik** [OfficeDev/microsoft-graph-docs#127]
OrderBy DESC in this formula https://graph.microsoft.com/v1.0/users?$orderBy=displayName%20desc is ignored, it shows items ordered ASC

**Comment by marych** [comment]
Thanks for reporting the issue. Sorting in descending order is not support, but should return an error message instead of ignoring the desc parameter. We'll fix that.

**Comment by keyur32** [comment]
@marych, please update and close this issue if addressed.

**Comment by marych** [comment]
This has been fixed - the above request now returns an error message explaining that OrderBy DESC is not supported.
