### ISSUE TITLE
post request to posts returns 504 on first attempt

### ISSUE THREAD

**Issue by dang2906** [OfficeDev/microsoft-graph-docs#133]
Hi,

When making a call to 'https://graph.microsoft,com/v1.0/tenant-id/groups/group-id/threads/thread-is/microsoft.graph.reply' in order to reply to a thread, i receive a 504 "Unknown Error" message as shown below. The post has the following body:

{
  "post": {
    "body": {
      "contentType": "html",
      "content": "Test comment"
    }
  }
}

'code=UnknownError'

 This only happens on the first call made for a particular bearer token. All subsequent calls are returned as successful. When the 504 error is received, the call is successful as shown by the post correctly being created, however, i assume due to some timeout or similar issue, the call is returning as failed.

Do you have any idea what is causing this? Or could it be fixed please.

Many Thanks,

**Comment by sriram-d** [comment]
Thanks for reporting this issue. Can you please share the entire body of the 504 response? It contains data (request-id and timestamp) that will help us investigate further.

**Comment by dang2906** [comment]
Thanks for your reply. Here is the information required:

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "8d0555e2-a66a-4aca-819b-b338cade0dfb",
      "date": "2016-02-22T09:03:11"
    }
  }
}

Thanks.

**Comment by Siern** [comment]
I have begun receiving those today.  It appears there are some serious issues with the API as very simple requests are bouncing between 400ms to over 20000ms!!

example:
https://graph.microsoft.com/v1.0/me/calendargroups  
response time: 20405ms
```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "406307c1-8746-467e-9c40-0471c1f395c6",
            "date": "2016-03-08T16:41:48"
        }
    }
}
```
But seeing "Exchange - Service degraded - EX44052" status, I assume this message should be some sort of time-out.

**Comment by sriram-d** [comment]
There are some known performance issues with accessing conversations of group. It is already being addressed and should be deployed in a few months. In the interim, some fine tuning has been done to reduce the number of 504 responses. However, the latency can still be high until proper fixes land. Let us know your comments on experience after today.
