### ISSUE TITLE
@content.downloadUrl is now @microsoft.graph.downloadUrl

### ISSUE THREAD

**Issue by Mike-Bell** [OfficeDev/microsoft-graph-docs#134]
http://graph.microsoft.io/docs/api-reference/v1.0/api/item_downloadcontent (and other places in the docs?) suggests `@content.downloadUrl` is returned on items. This property name was changed to `@microsoft.graph.downloadUrl`

**Comment by rgregg** [comment]
I've updated the content in the GitHub, and the website will pick up the change next time it's refreshed.
