### ISSUE TITLE
InternalServerError on incorrect POST queries

### ISSUE THREAD

**Issue by MiroJanosik** [OfficeDev/microsoft-graph-docs#138]
Some incorrect POST queries are not handled and return "InternalServerError".

I know it is returned for queries where "json" should be in the parameter and it is not. As example:
https://graph.microsoft.com/v1.0/users/3ff4c237-7604-4ac8-8fc6-15a533363975/messages
{
    "body" : "Hello dear aunt Emma"
} 

Result is:

>     "error": {
>         "code": "InternalServerError",
>         "message": "Object reference not set to an instance of an object.",
>         "innerError": {
>             "request-id": "352f1e37-d827-4186-a8d7-00c723948946",
>             "date": "2016-03-01T10:05:02"
>         }
>     }

"body" should be json { "contentType": "text", "content": "Test 4" }.  But I guess that "Object reference not set to an instance of an object" is not a correct behavior ;-)

**Comment by marych** [comment]
This was fixed last week and such requests now return BadRequest/400 with "Property body in payload has a value that does not match schema." message.
