### ISSUE TITLE
Typo in AD Graph queries doc

### ISSUE THREAD

**Issue by viv-liu** [OfficeDev/microsoft-graph-docs#141]
https://msdn.microsoft.com/library/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#CommonQueries

Under "Other Query operations", table row "Request and Filter for a user with displayName equal to “Jon Doe”, https://graph.windows.net/contoso.com/**_u_**sers?$filter=displayName eq 'Jon Doe'&api-version=1.6

It is currently an uppercase U, which is not a valid request.

**Comment by viv-liu** [comment]
![image](https://cloud.githubusercontent.com/assets/4438973/13473886/481cb3dc-e070-11e5-832b-4fb83aab5779.png)

**Comment by dkershaw10** [comment]
Thanks.  Good catch - this is actually a type on the AAD Graph documentation.  This repo is for Microsoft Graph only.  Will forward your issue to the right person to get this fixed in the AAD docs.

**Comment by yinaa** [comment]
no op for this repo
