### ISSUE TITLE
Docs should consistently load over HTTPS

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#169]
So there are currently a number of ways to get to `graph.microsoft.io` -- one of the routes uses inconsistent security and causes [mixed content](https://developer.mozilla.org/en-US/docs/Security/Mixed_content) warnings

There's

- :x:   `http://graph.microsoft.io` -- uses HTTP **
- :heavy_check_mark:  `https://graph.microsoft.io` -- uses HTTPS
- :heavy_check_mark:  `http://graph.microsoft.com` -- hits `301 Moved Permanently` -> then uses HTTPS
- :heavy_check_mark:  `https://graph.microsoft.com` -- uses HTTPS, hits `301 Moved Permanently` and continues to use HTTPS

** Since we already have this infrastructure secured by HTTPS we should use it always, and by default

**Comment by keyur32** [comment]
I think this was resolved some time back. Please let me know if you still see issues like these.
