### ISSUE TITLE
Function parameter ordering

### ISSUE THREAD

**Issue by kevklam** [OfficeDev/microsoft-graph-docs#207]
The reminderView function seems sensitive to ordering of startDateTime/endDateTime - should either document or fix.

**Comment by angelgolfer-ms** [comment]
Hi kevklam,
Thank you for your input. I also verified that's the current behavior - if you swap the order and specify endDateTime before startDateTime, you'd get an error. I have relayed this to the product team and we'll make updates accordingly. Thank you again for your patience.

Angelgolfer-ms
