### ISSUE TITLE
User/Photo/GetPhoto menu item linked to photo_get.md instead of profilephoto_get.md

### ISSUE THREAD

**Issue by marych** [OfficeDev/microsoft-graph-docs#23]
There is v1.0/api/photo_get.md and v1.0/api/profilephoto_get.md.

The navigation menu has profilePhoto and not photo resource (v1.0/resources/profilephoto.md), but the sub menu items refer to the photo and not profilePhoto APIs.
“Get photo” should be linked to v1.0/api/profilephoto_get and not v1.0/api/photo_get.

**Comment by sumurthy** [comment]
driveItem has photo and that's what the photo_get is referring to. profilePhoto is coming form users, groups, etc. 
The file names are based on the 'type' and not the name of the property.. hence photo* is from driveItem object.
