### ISSUE TITLE
Wrong content-type of notification callback payload

### ISSUE THREAD

**Issue by vanta** [OfficeDev/microsoft-graph-docs#232]
As described here: http://graph.microsoft.io/en-us/docs/api-reference/beta/api/subscription_post_subscriptions the content of subscription notification callback payload is in JSON format (basing by content, but not state explicitly). But for some reason, it is sent as `text/plain;charset=utf-8`, which makes it unable to automatically map by JSON mappers.

**Comment by garethj-msft** [comment]
Hi Vanta.  Only the first request (the validation request) is `text/plain` as that doesn't contain JSON.  The actual notifications should be coming through with a content type of `application/json; charset=utf-8`.

**Comment by vanta** [comment]
Ok, Now I see it. The problem was that my endpoint for notifications consumed also `POST`s from validation requests. How about changing validation requests to `GET` as they have no content, have query param, return content and are idempotent? Looks like perfect `GET` request description :)

**Comment by garethj-msft** [comment]
Glad to hear you worked it out Vanta.  You make a good point about `GET`, but unfortunately, that would be a breaking change for folks who have already implemented `POST`, so we couldn't do it until we move to V2.0 of the API at some future point.

**Comment by vanta** [comment]
@garethj-msft Make sense.
