### ISSUE TITLE
Unclear sample about drive invite action

### ISSUE THREAD

**Issue by VitorX** [OfficeDev/microsoft-graph-docs#252]
Does any one know the value of "permissionIdentityType-value" in the sample:

`POST https://graph.microsoft.com/v1.0/drive/root/Microsoft.Graph.invite
Content-type: application/json
Content-length: 313

{
  "recipients": [
    {
      "email": "email-value",
      "alias": "alias-value",
      "objectId": "objectId-value",
      "permissionIdentityType": "permissionIdentityType-value"
    }
  ],
  "message": "message-value",
  "requireSignIn": true,
  "sendInvitation": true,
  "roles": [
    "roles-value"
  ]
}`

Check the document link [here](http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_invite):

**Comment by marych** [comment]
The invite action is only available in in the beta version of the API - see http://graph.microsoft.io/en-us/docs/api-reference/beta/api/item_invite. It will be added to V1.0 in the future and this page should then be updated and linked. How did you find it under V1.0 - is it linked anywhere?

**Comment by VitorX** [comment]
Please check the link:[http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_invite](http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_invite)

**Comment by marych** [comment]
I saw the page, but it should not be linked from the menu or any other page. If you see a reference to it from anywhere please let us know and we'll remove the reference. 
When the invite action is added to /v1.0 we'll update https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/item_invite.md and add references/links to it in the relevant places.

**Comment by gerarde** [comment]
It's linked from here:
https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/driveitem.md

**Comment by marych** [comment]
Thanks @gerarde! @rgregg - we need to remove the "Add permissions" method link from v1.0 documentation.

**Comment by VitorX** [comment]
@marych It is linked from the Microsoft Graph official document: https://graph.microsoft.io/en-us/docs/overview/overview. You can navigate by click 'beta reference'->OneDrive->DriveItem->Add Permissions.

I also failed with the API with beta version like below:
POST: https://graph.microsoft.com/beta/me/drive/items/01G4KMWSF3L7A4BUBPYZA33DMFEOORTPG6/invite

{
  "recipients": [ { "email": "emailAddressHere" } ],
  "message": "Here's the file I mentioned during our meeting.",
  "requireSignIn": true,
  "sendInvitation": true,
  "roles": [ "write" ]
}

**Comment by marych** [comment]
@VitorX - we'll remove the link from /v1.0 driveItem docs. What error did you get from /beta?

**Comment by VitorX** [comment]
@marych It is working now. Thanks:)
