### ISSUE TITLE
Graph extensibility model?

### ISSUE THREAD

**Issue by mmaitre314** [OfficeDev/microsoft-graph-docs#266]
Is it possible to define custom nodes and edges in the graph? I'd like to add Git Commits for instance, linked to users and storing info like repo, date, modified files.

**Comment by dkershaw10** [comment]
There is some limited capability for this on /beta, but this is an area we'll be working on. Anyways, for questions on functionality of the Graph, please use StackOverflow and tag with [microsoftgraph].  This repo (and filing issues) is really more about issues with the documentation.

**Comment by mmaitre314** [comment]
Thanks. Will do.
