### ISSUE TITLE
Daemon authorization

### ISSUE THREAD

**Issue by mmaitre314** [OfficeDev/microsoft-graph-docs#267]
Is it possible to give daemons (apps without users) access to the graph? I'd like to have an Azure WebJob listen on some WebHook and populate nodes and edges into the graph automatically.

**Comment by dkershaw10** [comment]
It is possible, for some entity types, to support daemon apps (apps without users or app-only access). It's described here:  https://graph.microsoft.io/en-us/docs/authorization/app_only. For questions on functionality on the Graph, please use StackOverflow and tag with [microsoftgraph].  This repo (and filing issues) is really more about issues with the documentation.
