### ISSUE TITLE
Group calendar docs missing info on updating and deleting events

### ISSUE THREAD

**Issue by dkershaw10** [OfficeDev/microsoft-graph-docs#28]
Is this missing a set of links?

**Comment by martellaj** [comment]
Yes, I only see create and list events on the [group resource](http://graph.microsoft.io/docs/api-reference/v1.0/resources/group).

**Comment by angelgolfer-ms** [comment]
Yes, I think get an event, update event and delete event are applicable to group events as well, but are not shown in the TOC. I'll get them added to the TOC.

**Comment by angelgolfer-ms** [comment]
Close this issue for now, with the current design.
