### ISSUE TITLE
Can't update profile photo with Microsoft Graph API (beta)

### ISSUE THREAD

**Issue by biste5** [OfficeDev/microsoft-graph-docs#298]
Using `beta` REST endpoint for Unified / MS Graph APIs to update user's profile picture  
`PATCH /me/photo/$value`

returns a successful status code 204 (not 200 as per documentation #131 ), but operation has no real effect.
Switching to `v1.0` endpoint picture is immediately updated at least in OWA

**Comment by marych** [comment]
Hi @biste5. One of the recently enabled features on /beta is AAD fallback for user photo requests (see https://graph.microsoft.io/en-us/changelog): 
"Azure Active Directory is now used as a fallback for /beta/users/id/photo requests when the Outlook is unable to service the request for cases like the user has no mailbox license or tenant does not have an Exchange Online subscription. NOTE: this fallback is available for both GET and PATCH".
It sounds like your PATCH request fails to save the photo in Outlook and thus we fallback to storing it in AAD. That should not be the case if you're able to update the photo via /v1.0, which only attempts to store the photo in the Outlook store. Could you please let me know request-id and timestamp of your /beta and /v1.0 calls for the same user?

**Comment by biste5** [comment]
Hi, thanks for your reaction @marych . It's new to me, and very interesting, this AAD fallback you point out. I'd like to know more about how profile pictures are stored in AAD, and that story...
I'm actually doing different tests for different scenarios we have by customers, and behavior aren't consistent thus clear. For instance, if I update my picture via MSGraph, is it supposed to propagate also to SharePoint / Delve ?
I will perform some new test with our mobile client and provide details as you request. For now I can confirm tests were done with a user having a valid E license.

**Comment by biste5** [comment]
Client Request Id: bd028bb8-6734-48d5-a229-66add36065e2
Timestamp: 6/8/2016 9:57:04 PM +00:00

(so about 10 hours ago, and haven't changed. Response was successful)

**Comment by marych** [comment]
I checked in logs that this request failed to save the photo in Outlook with "(405) Method Not Allowed" error. You should see it returned to the client when using the /v1.0 endpoint for the same user. I'll follow check with the Outlook team why 405 was returned in this case.

**Comment by marych** [comment]
@biste5 There was a change in Outlook behavior for the /beta endpoint and photo uploads are now only supported via the PUT method. PATCH is no longer allowed. We'll update the documentation accordingly. 
For /v1.0 both PATCH and PUT are supported.

**Comment by marych** [comment]
@angelgolfer-ms https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/beta/api/profilephoto_update.md is the doc to be updated from PATCH to PUT.

**Comment by angelgolfer-ms** [comment]
Thanks, @marych , the docs have been updated per #357 . @biste5 , we apologize for the delay and thank you for your continued support.

**Comment by biste5** [comment]
Thanks @marych and @angelgolfer-ms for your support!
I can confirm now beta endpoint updates the profile picture correctly, so issue could be indeed closed. I was just still performing some tests to ensure both endpoints can update the picture in Delve/SP too, but this is taking a bit of time from me, to perform correct tests and waiting to verify how long it takes to propagate.

**Comment by angelgolfer-ms** [comment]
@biste5 , good to hear that updating profile picture is working as expected!

Cheers,
angelgolfer-ms
