### ISSUE TITLE
Accessing Shared with Me item gives 401 Unauthorized

### ISSUE THREAD

**Issue by NeosQuanta** [OfficeDev/microsoft-graph-docs#299]
My reference is this documentation : https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/drive_sharedwithme
I want to get a list of 'Shared with Me' items of the signed-in user and provide a button containing downloadUrl to download the item of the list. The problem is I can't get the downloadUrl.
What I am doing is :
1. Request `GET /me/drive/sharedWithMe`This call is a success, the response is generally the same as in the documentation. Here's a part of the response : 
```
{
    "@odata.type": "#microsoft.graph.driveItem"
    "createdDateTime": "0001-01-01T00:00:00Z"
    "id": "01TWWV5W37UJKHFIUBZZBZDEHOJNVOEZVP"
    "lastModifiedDateTime": "2016-05-20T05:39:00Z"
    "remoteItem": {
        "file": {}
        "id": "01TWWV5W37UJKHFIUBZZBZDEHOJNVOEZVP"
        "name": "2NF.PNG"
        "parentReference": {
            "driveId": "b!XxxqXZ1tqUGbTG6lCAZp8lCk94i3qvhJt1qf0GJTLQf11toCmqOoS4hkfSFKzG0F"
       }-
        "size": 0
    }-
    "size": 0
}
```
From the response I get the "driveId" and the "id" of the item. They will be used in step 2.

2.Request `GET /drives/<remoteItem.driveId>/items/<id>`
This is how I get the downloadUrl, but this call gives me this 401 Unauthorized error response :

```
{
    "error":{
        "code":"-2147024891, System.UnauthorizedAccessException",
        "message":"Access denied. You do not have permission to perform this action or access this resource.",
        "innerError":{
            "request-id":"64f90e20-92a4-4002-8833-da5de026c076",
            "date":"2016-05-27T10:30:58"
        }
    }
}
```

To fix this, I have attempted to enable some permissions : Files.Read.All & Sites.Read.All .
Here is a part of my decoded access_token to see all of my enabled permissions

`scp: "Calendars.ReadWrite Contacts.ReadWrite Directory.ReadWrite.All Files.Read Files.Read.All Files.ReadWrite Group.ReadWrite.All Mail.ReadWrite Mail.Send Sites.Read.All User.Read User.Read.All User.ReadWrite",`

What I am asked here is : why it gives me 401 Unauthorized error? and how to fix it?

Thanks in advance and sorry for my bad English.

**Comment by mimisasouvanh** [comment]
Hi @NeosQuanta  Thank you for reaching out! Did you try GET /me/drive/items/{item-id}/content as in the documentation https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_downloadcontent ?
Note that you don't need the drive-id.

**Comment by mimisasouvanh** [comment]
Hi @NeosQuanta Are you using a personal site host like https://microsoft-my.sharepoint.com, or something like http://microsoft.sharepoint.com? You might not have the proper permission/rights on the web. Files.ReadWrite gives permissions to apps but users would still need permissions to the website as well.

**Comment by NeosQuanta** [comment]
Hi @mimisasouvanh Thanks for the response. I tried `GET /me/drive/items/{item-id}/content` but it still gives same error. I am using the personal one like https://microsoft-my.sharepoint.com .

I forgot to mention this, when I tried to access the shared item manually with `GET /users/<id | userPrincipalName>/drive/root/children`, it gives me the list of items that I can access(the downloadUrl is there). So i think the permission setting is right(maybe wrong), and of course, this method is not practical because the userId | principalName not contained in the sharedWithMe response.

But on the other hand, If the permission is still not sufficient, then how do I give user permission to the website? Is it in the application permission in the Azure Portal settings?

Sorry for my bad English.

**Comment by mimisasouvanh** [comment]
To give permission to users, the user must be logged in on whatever browser you are using. I hope this works.

**Comment by NeosQuanta** [comment]
@mimisasouvanh Thanks for the response as always. I've logged in as user through site like login.microsoftonline.com (to get the access_token) and to make sure of your tips, I also logged in to https://mytenantname-my.sharepoint.com, but unfortunately it doesn't work. 

I can get the item successfully using `GET /users/<id | userPrincipalName>/drive/items/<item-id>` (manually), is this giving you any clue? Maybe the permission needed for GET /users/<id | userPrincipalName>/drive/items/<item-id> and GET /drive/items/<item-id> is different?

**Comment by mimisasouvanh** [comment]
OK - a colleague of mine looked at your issue, and here is his suggestion: the web site you need permission for is https://binussianorg.sharepoint.com. Your call to Graph gets routed with that URL. Please try logging in to this site.

**Comment by NeosQuanta** [comment]
@mimisasouvanh That's it. I never thought the https://tenant.sharepoint.com is also used, because when I access outlook.office.com and click Onedrive icon, the site used there is https://tenant-my.sharepoint.com.

When I open the site, it gives me this error message : "You need permission to access this site."
All that's left is for me to contact my admin to consider modifying the permission then.
Thanks for the guidance.
