### ISSUE TITLE
Unrendered special chars in docs

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#30]
From https://graph.microsoft.io/docs/api-reference/v1.0/resources/event

<img width="1110" alt="screen shot 2015-11-23 at 3 25 20 pm" src="https://cloud.githubusercontent.com/assets/990063/11353313/e1798e1a-91f6-11e5-88aa-1250b0458d5f.png">

There are likely other pages with this problem.

**Comment by iambmelt** [comment]
Although this is a tooling issue - as a follow up, the [Message docs](http://graph.microsoft.io/docs/api-reference/v1.0/resources/message) have this too.

![screen shot 2015-12-09 at 9 48 49 am](https://cloud.githubusercontent.com/assets/990063/11694573/ac92f48c-9e5f-11e5-8da2-3b2694aec789.png)

**Comment by DianeD** [comment]
fixed--these tags are not visible
