### ISSUE TITLE
Members not returned from mail-enabled security groups

### ISSUE THREAD

**Issue by ArieJones** [OfficeDev/microsoft-graph-docs#354]
When trying to pull a list of members for a mail-enabled security group we are getting zero records returned. 

https://graph.microsoft.com/beta/groups/44a23765-75ae-4b29-843e-9a7c2c4712a3

although this group has 1 assigned member. We have attempted this with other similar mail-enabled security groups as well as using the online graph explorer. None of them function correctly even though the documentation says that 

> 
Users, contacts, and groups that are members of this group. HTTP Methods: GET (supported for all groups), POST (supported for security groups and mail-enabled security groups), DELETE (supported only for security groups) Read-only. Nullable.

So this should be possible.

**Comment by marych** [comment]
Hi @ArieJones. As per https://graph.microsoft.io/en-us/docs/api-reference/beta/api/group_list_members the request to get the list of group members is `GET /groups/<id>/members`, e.g. https://graph.microsoft.com/beta/groups/44a23765-75ae-4b29-843e-9a7c2c4712a3/members. The same pattern applies to all the other group relationships listed in the documentation. You need to append the relationship name segment in the URL to get the list of related entities.

**Comment by ArieJones** [comment]
Please reopen this..... I was providing you the link to the group so that you could research what the issue was... 
Using this 
https://graph.microsoft.com/beta/groups/44a23765-75ae-4b29-843e-9a7c2c4712a3/members

You get the following from Graph Explorer.. 


{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#directoryObjects",
    "value": []
}

**Comment by marych** [comment]
You could please provide request-id and timestamp of the request? How do you confirm that the group has an assigned member?

**Comment by ArieJones** [comment]
How do I get the request-id from the graph explorer? I just now did another query with the same results. 

We confirmed that there are members in the group by looking a the Azure Portal. This group has one assigned member.

**Comment by ArieJones** [comment]
Ah-ha Response Headers 

{
    "cache-control": "private",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "49f96f7c-6dc0-461d-b969-9200fd47c3b3",
    "client-request-id": "49f96f7c-6dc0-461d-b969-9200fd47c3b3"
}

**Comment by marych** [comment]
Thank you for reporting the issue @ArieJones. It's a recent regression related to organizational contacts not being returned by the /beta version. The object that is a member of that group is a contact. Right now /beta/groups/id/members returns only group and user members. We're working on a fix. 
As a note - /v1.0/groups/id/members is not expected to return contact members as the orgContact entity type is only defined in /beta and not in /v1.0.

**Comment by ArieJones** [comment]
Any kind of update on this? We have a project that is in a holding pattern right now. 

Thanks,
AJ

**Comment by marych** [comment]
We have the fix ready, but it will take a few weeks to have it deployed globally. It involves changes in a core Azure Active Directory component and since only /beta is affected it will not be rolled out in emergency mode. We're sorry for the long wait time.

**Comment by marych** [comment]
The fix was deployed on 7/12 and the issue should no longer occur.
