### ISSUE TITLE
Ambiguous "Tasks" language in documentation navigation

### ISSUE THREAD

**Issue by cbales** [OfficeDev/microsoft-graph-docs#365]
Currently there is some ambiguity in the language used to document [Tasks](https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/task). It is not made clear that these are _Planner_ tasks and not _Outlook_ tasks. You can see in Office365 that Tasks [has its own tile](https://cloud.githubusercontent.com/assets/2273297/16346272/3f173124-39fb-11e6-8924-ea8a0faefe16.PNG), but is a sub product of Outlook.

I would argue that "Tasks" should be under a "Planner" heading to reference the product, similar to how OneNote, Excel, et. al. are handled.

**Comment by keyur32** [comment]
Thank you for the feedback. We are looking at the IA of the Table of contents and titles and will take this feedback as part of that conversation.
