### ISSUE TITLE
Is the Plan/Task API available for Microsoft Graph? 

### ISSUE THREAD

**Issue by VitorX** [OfficeDev/microsoft-graph-docs#370]
Always get the error **The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable** when I get the plans like below:

GET:https://graph.microsoft.com/beta/me/plans

Refer to the [document](https://graph.microsoft.io/en-us/docs/api-reference/beta/api/user_list_plans)

**Comment by marych** [comment]
Hi @VitorX - could you please provide request-id and timestamp for investigation?

**Comment by VitorX** [comment]
Thanks for your response. The issue seems be fixed. The API works now.
