### ISSUE TITLE
Unable to create mailEnabled groups

### ISSUE THREAD

**Issue by callmeradical** [OfficeDev/microsoft-graph-docs#372]
The documentation for create groups incorrectly states that you are able to create a distribution list by settings SecurityEnabled to False and MailEnabled to True.

The response is 
```json
{
	"error": {
		"code": "Request_BadRequest",
		"message": "The service does not currently support writes of mail-enabled groups. Please ensure that the mail-enablement property is unset and the security-enablement property is set.",
		"innerError": {
			"request-id": "52813dc7-e653-4fa3-9edf-bf9efa5dc718",
			"date": "2016-06-30T18:27:06"
		}
	}
}
```

**Comment by marych** [comment]
Leave a comment

**Comment by callmeradical** [comment]
This did not solve the issue. Documentation is still lacking in this area. The API does not behave anywhere near close to the documentation.

Particularly 

"Default is false. Indicates if people external to the organization can send messages to the group. You can set this property in a PATCH request for the group; do not set it in the initial POST request that creates the group."

You cannot allowExternalSenders via the API.
