### ISSUE TITLE
Are we supposed to submit issues on the actual API code here or just documentation?

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/microsoft-graph-docs#388]
I can't tell if I'm supposed to be submitting issues on the just the documentation or report issues on the API code not functioning correctly.  This is the "microsoft-graph-docs" repository but I am seeing code issues being reported.

I see this in other GitHub repos that link from Microsoft docs also. It's confusing because there is User Voice too, and forums.

Thanks,
Jim

**Comment by angelgolfer-ms** [comment]
Hi @jbarr33 , 
Please submit:
- Documentation issues or actual pull requests for the docs on GitHub
- Code and API issues on [Stackoverflow](http://stackoverflow.com/questions/tagged/microsoftgraph), tagging them with "microsoftgraph"
- Suggestions and requests for features, code samples, architecture guidance on [UserVoice](https://officespdev.uservoice.com/)

We're working on clarifying this messaging, meanwhile, thank you for your continued support!

Angelgolfer-ms
