### ISSUE TITLE
Cannot access SharedWithMe Folder

### ISSUE THREAD

**Issue by Ryanz20** [OfficeDev/microsoft-graph-docs#445]
Hello,
I am trying to download the content of the items of a shared folder using the graph api. I am able to retrieve the basic details by using the /v1.0/me/drive/sharedWithMe request.

![2016-08-29_10h40_45](https://cloud.githubusercontent.com/assets/21312695/18055246/11929104-6dd5-11e6-8ec6-5bb1d7a8e4b0.png)

However when I try and request the contents of the folder using the '/drives/remoteItem.driveId/items/id' request I get a 'itemNotFound' error code.

/drives/b!SuVijei8UUiLXWR4XeJPFe-SS3gbCDVJuXZLcatX7Ikm3BPqZMVJTLOW4rsDD7B2/items/01GB75254SYRXS4C7C25HLIWFMXFY7HWB3

Any ideas what is going on?
Thanks!

**Comment by MIchaelMainer** [comment]
Hello @Ryanz20,

Thank you for posting this question. This repo is for the Graph API documentation. Please feel free to ask questions about the documentation, or make changes to the documentation in this repo. For questions about the API, please post the question in StackOverflow using the [microsoftgraph](http://stackoverflow.com/questions/tagged/microsoftgraph) tag. That way, the answer to your question will be more accessible to other people in the community. Once you've posted your question, link to it from here and I'll provide the answer.

With regards,
Michael

**Comment by Ryanz20** [comment]
Hi Michael,
Sorry for the confusion.

I have posted my question on stackoverflow [here](http://stackoverflow.com/questions/39213927/cannot-access-sharedwithme-folders-via-microsoft-graph-api).

Thanks!

**Comment by MIchaelMainer** [comment]
@Ryanz20, no problem. Thank you for posting on StackOverflow! If the documentation was the source of your confusion, or if there is a way that we could improve it, we'd love to hear your feedback, or take your pull request.

**Comment by MIchaelMainer** [comment]
Actually, it looks like the documentation should refer to remoteItem.parentReference.drive.Id as the segment value. Thank you for bringing this up.
