### ISSUE TITLE
Create groups is not exposed in the online web docs

### ISSUE THREAD

**Issue by dkershaw10** [OfficeDev/microsoft-graph-docs#54]
Although there is a Groups_post_groups.md topic, it's not referenced by the online docs.  We don't mention anywhere how to create a new group

**Comment by martellaj** [comment]
So [this](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_post_groups.md) is the topic that isn't exposed, right? That's the same topic that needs to be updated with respect to issue #55, right?

**Comment by angelgolfer-ms** [comment]
@yinaa - I updated the group_post_groups topic per #55. Please add that topic to the TOC.

**Comment by yinaa** [comment]
Fixed, both (a) and (b)
