### ISSUE TITLE
Group topics need more information on O365 groups

### ISSUE THREAD

**Issue by dkershaw10** [OfficeDev/microsoft-graph-docs#55]
In the group creation API and group resource topics, there are some explicit mentions that Microsoft Graph only allows creation of security groups, which is incorrect.  This may appear in some of the other group topics too.

**Comment by martellaj** [comment]
Can you give us more information about which groups *can* be created? I think this was taken from the [Azure docs](https://msdn.microsoft.com/en-us/Library/Azure/Ad/Graph/api/groups-operations).

**Comment by dkershaw10** [comment]
Security groups, unified (O365) groups and dynamic groups.  For the last 2 see the groupTypes property.  Also securityEnabled should not be set when creating an O365 group.  Does that help?
