### ISSUE TITLE
Chunked/large file uploads unavailable?

### ISSUE THREAD

**Issue by Mike-Bell** [OfficeDev/microsoft-graph-docs#59]
http://graph.microsoft.io/docs/api-reference/v1.0/api/item_uploadcontent Specifies that 4MB is the max file upload size support by *this method*. The OneDrive API supports larger file uploads via a chunked upload mechanism: https://dev.onedrive.com/items/upload_large_files.htm. I was hoping that the unified API would support this feature, but attempting to create an upload session gives me a `400: Unsupported segment type` response. Am I correct in surmising that the unified API does not support uploads greater than 4MB in any fashion? If so, it would be nice if the docs more directly addressed the fact that this feature does not exist in any capacity, as it is a pretty basic expectation for a lot of uses I can think of.

**Comment by mimisasouvanh** [comment]
Hi Mike, 
Thanks for the comments! The plans to support chunked uploads is in our backlog. I'll update the docs to specifically state that chunked uploads is not yet available.

**Comment by Mike-Bell** [comment]
Thanks!

**Comment by EdAlexander** [comment]
Any updates on timing for large file support (chuncked upload)?

**Comment by coreyrowell** [comment]
Updates on when > 4mb uploads will be supported?
