### ISSUE TITLE
Incorrect URLs in Graph Docs

### ISSUE THREAD

**Issue by CodeMoggy** [OfficeDev/microsoft-graph-docs#61]
It looks like the docs are wrong on the site:
https://graph.microsoft.io/docs

Examples still refer to items but should it not be children, e.g. 

https://graph.microsoft.com/v1.0/me/drive/root/items/foo.txt/lastModifiedByUser
should be 
https://graph.microsoft.com/v1.0/me/drive/root/children/foo.txt/lastModifiedByUser

**Comment by mimisasouvanh** [comment]
Hi Richard, the call you are referring to must first GET the item (https://graph.microsoft.io/docs/api-reference/v1.0/api/item_get) and then use the OData query parameter _select_ to return the specific property you want from the item (http://graph.microsoft.io/docs/overview/query_parameters). It is not listing the children of an item. The call should be: 
GET https://graph.microsoft.com/v1.0/me/drive/root/items/foo.txt?select=lastModifiedByUser

**Comment by rgregg** [comment]
@CodeMoggy Yes, you have the right syntax there. You need to use /children or :/{filename}: to address a particular file inside a folder. The /lastModifiedByUser can work either the way you specified or the way @mimisasouvanh used it, depending on your goal. In Graph, doing /lastModifiedByUser will return the user principal information from the directory without returning any information about the file. Mimi's way of doing it would return the file information along with the full details of the lastModifiedByUser.

@mimisasouvanh Can we make sure any references to /items/{filename} are removed from the docs?

**Comment by CodeMoggy** [comment]
In some examples (e.g. Excel REST API) I have seen the name of the file replaced by the id of the document. What is the correct syntax when using /children? Is it drive/root/children/564655GUTG/workbook/worksheet/ where 564655GUTG is the id of the document...are quotes or brackets required to identify the identifier as an id rather than the name of the document?
Thank you
On 4 Dec 2015 04:09, Ryan Gregg <notifications@github.com> wrote:@CodeMoggy Yes, you have the right syntax there. You need to use /children or :/{filename}: to address a particular file inside a folder. The /lastModifiedByUser can work either the way you specified or the way @mimisasouvanh used it, depending on your goal. In Graph, doing /lastModifiedByUser will return the user principal information from the directory without returning any information about the file. Mimi's way of doing it would return the file information along with the full details of the lastModifiedByUser.

@mimisasouvanh Can we make sure any references to /items/{filename} are removed from the docs?

**Comment by rgregg** [comment]
If you have a file's ID, you should use /drive/items/{file-id} to access the item, and then use the Excel API from there.

If you have a filename and path, you can do it two different ways:
1. If the file is in a directory that's easy to access, you can do /drive/root/children/{filename}/workbook/worksheet
2. If the file path is known, you can do /drive/root:/path/to/file:/workbook/worksheet

No quotes or brackets are required, although proper URL encoding of the filenames / path is required. More details about filename encoding specifics is available here: https://dev.onedrive.com/misc/path-encoding.htm

**Comment by CodeMoggy** [comment]
Thanks Ryan
On 4 Dec 2015 06:02, Ryan Gregg <notifications@github.com> wrote:If you have a file's ID, you should use /drive/items/{file-id} to access the item, and then use the Excel API from there.

If you have a filename and path, you can do it two different ways:
1. If the file is in a directory that's easy to access, you can do /drive/root/children/{filename}/workbook/worksheet
2. If the file path is known, you can do /drive/root:/path/to/file:/workbook/worksheet

No quotes or brackets are required, although proper URL encoding of the filenames / path is required. More details about filename encoding specifics is available here: https://dev.onedrive.com/misc/path-encoding.htm

**Comment by mimisasouvanh** [comment]
Thanks for clarifying, Ryan! I checked the docs and made sure there weren't /items/{filename} in the documentation, and corrected the link in https://graph.microsoft.io/docs.
