### ISSUE TITLE
'Create calendarView' links to wrong documentation

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#66]
From http://graph.microsoft.io/docs/api-reference/v1.0/resources/user

Clicking 'create calendarView' takes you to the 'Create Event' documentation

![screen shot 2015-12-07 at 2 15 48 pm](https://cloud.githubusercontent.com/assets/990063/11641470/3d8a51ca-9ced-11e5-9c33-626e1d4c8db5.png)

![screen shot 2015-12-07 at 2 16 08 pm](https://cloud.githubusercontent.com/assets/990063/11641503/639350ba-9ced-11e5-82b3-bcc6b9ad1e67.png)

**Comment by martellaj** [comment]
Looks like the link is correct, but the topic is not. @angelgolfer-ms, do you have documentation on dev.outlook.com for creating a calendarView that you can port over? Am I right in saying that the only things that need to be updated here are the topic title and description?

**Comment by angelgolfer-ms** [comment]
I started an internal thread to get confirmation. Were you able to get the generated syntax to work? I didn't.
