### ISSUE TITLE
What is the expected DateTime format?

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#67]
http://graph.microsoft.io/docs/api-reference/v1.0/api/user_reminderview requires a start & end time as params - what is the expected number format? The answer to this question likely affects https://github.com/OfficeDev/microsoft-graph-docs/issues/57

**Comment by angelgolfer-ms** [comment]
@iambmelt, a teammate owns this, but I can give it a shot and suggest you try a dateTime string like "2015-11-08T19:00:00.0000000". Also specify a Prefer: request header and specify a time zone as the default time zone for the reminders in the response.

**Comment by angelgolfer-ms** [comment]
@iambmelt, let me know if the updated content works.

**Comment by iambmelt** [comment]
Looks great - thanks @angelgolfer-ms @martellaj :+1:
