### ISSUE TITLE
Documentation indicates single item /manager may be a collection type?

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#68]
Per [`GET` /manager](http://graph.microsoft.io/docs/api-reference/v1.0/api/user_list_manager)

If successful, this method returns a 200 OK response code and **collection** of directoryObject objects in the response body.

but the sample response yields a single object

```json
{
  "objectType": "User",
  "id": "111048d2-2761-4347-b978-07354283363b",
  "accountEnabled": true,
  ...
  "city": "San Diego",
  "country": "United States",
  "department": "Sales & Marketing",
  "displayName": "Sara Davis",
  "givenName": "Sara",
  "jobTitle": "Finance VP",
  "mail": "SaraD@contoso.onmicrosoft.com",
  "mailNickname": "SaraD",
  ...
  "state": "CA",
  "streetAddress": "9256 Towne Center Dr., Suite 400",
  "surname": "Davis",
  "usageLocation": "US",
  "userPrincipalName": "SaraD@contoso.onmicrosoft.com",
  ...
}
```

my dev testing indicates this always returns a single `DirectoryObject` - can users really have multiple managers?

**Comment by marych** [comment]
@martellaj - GET manager returns zero or one directory object. The Response description should be updated not to indicate that it is a collection of directory objects.

**Comment by martellaj** [comment]
@marych, I'm no longer on the team; please assign future issues to @angelgolfer-ms (or whoever she says to assign them to). :rocket:
