### ISSUE TITLE
No scopes are specified for the /groups/<id>/memberOf endpoint in the documentation

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/microsoft-graph-docs#70]
The [documentation](https://github.com/OfficeDev/microsoft-graph-docs/blob/c4a5dbb50c5c6945a2fb721bc95afdec74ee450c/api-reference/v1.0/api/group_list_memberof.md) doesn't specify which scopes are required to call the **/groups/&lt;id&gt;/memberOf** endpoint.

**Comment by martellaj** [comment]
I'm assuming it's `Group.Read.All`. @dkershaw10, can you confirm that? I'll update the documentation when I get confirmation.

**Comment by waldekmastykarz** [comment]
:+1:
