### ISSUE TITLE
Retrieving the list of Office 365 Groups throws an error

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/microsoft-graph-docs#71]
If you try to retrieve the list of Office 365 Groups as specified in the [documentation](https://github.com/OfficeDev/microsoft-graph-docs/blob/c4a5dbb50c5c6945a2fb721bc95afdec74ee450c/content/overview/overview.md) you get the following error:

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Collection open properties are not supported in this release.",
        "innerError": {
            "request-id": "c26b9479-f410-460b-9659-543917690fb1",
            "date": "2015-12-08T19:11:11"
        }
    }
}
```

Request:
```
GET https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20%27unified%27)
```

Access token scopes: **Directory.Read.All Group.ReadWrite.All User.Read**

**Comment by martellaj** [comment]
The documentation says to use `'` instead of `%27`. It looks like the encoding of the apostrophe isn't supported to me. If you try the same request with apostrophes (from the docs), it should work fine.

@yinaa - should both work here? I'd assume if we use the encoding for space, that the encoding for apostrophe should work fine.

**Comment by waldekmastykarz** [comment]
The trouble with it is that tools like Postman automatically encode all special characters which makes it impossible to use non-encoded quotes. So when testing the Microsoft Graph with it, the first impression is that the API isn't working.
I can't tell to what extent developers on the different platforms can control encoding in the URLs of web requests but it seems that it would be the best to support both encoded and raw characters for the API to work everywhere.

**Comment by martellaj** [comment]
Completely agree, especially when encoding a space works as well. Yina should be able to provide some insight here.

**Comment by nickvdheuvel** [comment]
In JavaScript a `GET https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20%27unified%27)`, `GET https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20'unified')` or `GET https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a eq 'unified')` request still doesn't work. When will this issue be fixed?

**Comment by marych** [comment]
This was fixed last week - the encoded apostrophe is now accepted, so https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20%27unified%27) works.
