### ISSUE TITLE
Trying to get attachments from a Group post returns an error

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/microsoft-graph-docs#72]
Trying to get attachments from a Group post using the following request as described in the [documentation](https://github.com/OfficeDev/microsoft-graph-docs/blob/c4a5dbb50c5c6945a2fb721bc95afdec74ee450c/api-reference/v1.0/api/post_list_attachments.md):

```
GET https://graph.microsoft.com/v1.0/groups/123.../threads/AAQkADM.../posts/AAMkADMxY.../attachments
```

returns the following error:

```
{
    "error": {
        "code": "ErrorInvalidRequest",
        "message": "The OData request is not supported.",
        "innerError": {
            "request-id": "50f81d93-ec35-482c-9096-52a60ea223e5",
            "date": "2015-12-08T19:32:43"
        }
    }
}
```

Access token scopes: **Directory.Read.All Group.ReadWrite.All User.Read**

**Comment by martellaj** [comment]
@waldekmastykarz continuing to kill the issue game. Thanks for the feedback!

@dkershaw10, @yinaa - is this operation supported right now?

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by angelgolfer-ms** [comment]
I ran into a similar issue as well. Pinged the product team again. Will post back after they verify. Appreciate your patience, @waldekmastykarz.

**Comment by angelgolfer-ms** [comment]
@waldekmastykarz, we verified there was a bug, the fix has already started rolling out to customers, and will be widely available in about 4 weeks. Thanks for keeping an eye out on customers having similar questions on this too!
