### ISSUE TITLE
App-only model walkthrough

### ISSUE THREAD

**Issue by justinyoo** [OfficeDev/microsoft-graph-docs#80]
Hi, Team.

When I did some research for Graph API, I could hardly find app-only samples while there are hundreds of sample apps using delegated permissions scope (requires users to sign in first). Therefore, I'd built a sample Web API app as App-only model and created a walkthrough document.

Would you mind me sending a pull request for this?

Cheers,
Justin

**Comment by martellaj** [comment]
Hi, @justinyoo. We have a topic on this already in the pipeline (actually already in the joem-app-only branch on this repo). Please feel free to take a look and let me know what you think. It should be available on the website sometime next week.

**Comment by justinyoo** [comment]
Hi, @martellaj Thanks for your comment. The difference between `service_or_daemon.md` in the `joem-app-only` branch and mine is that mine uses ADAL and actual ASP.NET 5 sample code. Could you have a look at my one, [AspNetWebApiAppOnly.md](https://github.com/justinyoo/microsoft-graph-docs/blob/master/content/walkthroughs/AspNetWebApiAppOnly.md), before I send a pull request?

**Comment by martellaj** [comment]
Well the idea is to keep the topic as generic as possible so someone could write a service app in any language (for example, the sample I wrote that my topic uses is written in Node). Once I get my sample more polished, I'll update the topic to use that code, but at the end of the day, it's all REST based and does not require ADAL or ASP.NET features.

I think having multiple samples that demonstrate the concept on different platforms is a good idea. I'll have to discuss more with the team about how/if we can take on a sample from the community.

**Comment by justinyoo** [comment]
@martellaj I agree that the topic should be generic for apps in any language. I also agree the idea that multiple demo code samples for different platforms might be necessary. Actually, I brought up my sample app and demo code based on the current documents in the [Platform specific walkthroughs](https://graph.microsoft.io/docs/platform/rest) section.

It would be great if you have a discussion with your team and let the community (or me) know if sample code contribution from the community is acceptable or not. :-) I will be more than happy that my sample app is accepted (or at least forked for further enhancement) by MS.

**Comment by martellaj** [comment]
Hey, @justinyoo. So just wanted to loop you in to what we've been thinking. Community samples are a new space for us and we're working on a plan to effectively leverage what the community has to offer. Thanks again for taking initiative here; while we won’t accept your sample today, we’ll plan to reach out to you when we have a plan in place and operational. I’ll close the issue out for the time being.
