### ISSUE TITLE
Could not find a property named 'businessPhones' on type 'Microsoft.OutlookServices.Reminder'

### ISSUE THREAD

**Issue by scordonnier** [OfficeDev/microsoft-graph-docs#83]
If you try to get reminders using the following URL, you get an **Unsupported segment type** error :

https://graph.microsoft.com/v1.0/me/microsoft.graph.reminderView?startDateTime=2016-01-01T00:00:00&endDateTime=2016-01-31T23:59:59

I tried to use another URL but with the same result :

https://graph.microsoft.com/v1.0/me/reminderView?startDateTime=2016-01-01T00:00:00&endDateTime=2016-01-31T23:59:59

Otherwise, no problem with calendarView which uses the same syntax :

https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2016-01-01T00:00:00&endDateTime=2016-01-31T23:59:59

**Comment by angelgolfer-ms** [comment]
@scordonnier, reminderview is a function. It is different from calendarview in one way - the reminderview parameters should be enclosed in parentheses, and not as query parameters. Please take a look at the "HTTP Request" section in http://graph.microsoft.io/docs/api-reference/v1.0/api/user_reminderview.

**Comment by scordonnier** [comment]
I tried with https://graph.microsoft.com/v1.0/me/microsoft.graph.reminderView(endDateTime='2016-01-31T23:59:59',startDateTime='2016-01-01T00:00:00') but I receive this error :
```
{
  "error": {
    "code": "RequestBroker-ParseUri",
    "message": "Could not find a property named 'businessPhones' on type 'Microsoft.OutlookServices.Reminder'.",
    "innerError": {
      "request-id": "510aad1d-ea7b-4668-88fe-64e15dde5d7f",
      "date": "2015-12-15T10:19:16"
    }
  }
}
```

**Comment by angelgolfer-ms** [comment]
Did you verify the reminderView function call successfully returned you a collection of reminders? Just based on the error message, I am guessing somewhere, maybe from that function call, you're indeed able to access some reminder object. Are you trying to get the businessPhones property off the reminder object, as that error message says? The reminder object doesn't contain that property - see http://graph.microsoft.io/docs/api-reference/v1.0/resources/reminder. Only the Contact, User, and Organization object do.

**Comment by marych** [comment]
The last syntax is correct and the call fails because of a bug in the service. I'm working on a fix for it. 
As a temporary workaround that function can successfully be called on the /beta version: https://graph.microsoft.com/beta/me/microsoft.graph.reminderView(endDateTime='2016-01-31T23:59:59',startDateTime='2016-01-01T00:00:00')

**Comment by marych** [comment]
The issue has been fixed.
