### ISSUE TITLE
Filter events by start and end date gives an error

### ISSUE THREAD

**Issue by estruyf** [OfficeDev/microsoft-graph-docs#86]
If you want to filter events by including the start and end date property it gives and error:

```
{
  "error": {
    "code": "InternalServerError",
    "message": "An item with the same key has already been added.",
    "innerError": {
      "request-id": "d746f6e8-e35e-4fdb-be1f-5be2d19c5ad7",
      "date": "2015-12-16T08:43:08"
    }
  }
}
```
Used API endpoint: https://graph.microsoft.com/v1.0/me/events?$filter=Start/DateTime+ge+'2015-12-14T00:00:00Z'+and+End/DateTime+lt+'2015-12-28T00:00:00Z'

Using only the start or end date is working fine. Also including something else than the end/datetime like for example the subject is working fine: https://graph.microsoft.com/v1.0/me/events?$filter=Start/DateTime+ge+'2015-12-14T00:00:00Z' and subject eq 'meeting name' 

So it seems to be the combination with the start and end properties. This was working fine last week.

**Comment by marych** [comment]
Thanks Elio for reporting the issue. I'm working on a fix for it.

**Comment by marych** [comment]
The issue has been fixed.
