### ISSUE TITLE
Creating a subscription requires a HTTPS notificationUrl endpoint

### ISSUE THREAD

**Issue by estruyf** [OfficeDev/microsoft-graph-docs#87]
During the registration process of my subscriptions (webhook) I received the following message:

```json
{
"error": {
"code": "",
"message": "An error has occurred.",
"innerError": {
"request-id": "97978017-a6f1-444e-ae43-d44dcc43ba96",
"date": "2015-12-10T07:44:34"
}
}
}
```
In the end it was because I did specify a HTTP endpoint instead of HTTPS. If it is required that the notificationUrl need to use an HTTPS endpoint, the error should be a bit clearer.

**Comment by martellaj** [comment]
@estruyf, thanks for the feedback. We can definitely add a note in the documentation to make it clearer that the endpoint needs to be HTTPS. I will also pass this along to the devs about providing a better error with the API. Thanks!

**Comment by martellaj** [comment]
@garethj-msft, can you pass this along to the right PMs please?

**Comment by garethj-msft** [comment]
That would be me :-)

**Comment by garethj-msft** [comment]
We have a fix for this and other error messages in the works.

**Comment by garethj-msft** [comment]
We fixed this.  Please let us know if the error message isn't clear now.
