### ISSUE TITLE
'Get Item' doesn't document how to specify the target drive

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#89]
From: [here](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_get)

As we know, users can have multiple `drives` - their individual drive, their org drive, a Group drive, etc.

Per the documentation linked above, there are 3 ways to request items from a drive:

```
GET /drive/root
GET /drive/items/{item-id}
GET /drive/root:/{item-path}
```

How do I specify which drive id to use?

**Comment by iambmelt** [comment]
This lack of clarity exists around multiple `drive`-based actions, for instance...

"How do I specify which drive contains the thing...."

[...I'm creating?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_post_children)

[...I'm updating?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_update)

[...I'm deleting?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_delete)

[...I'm downloading?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_downloadcontent)

[...I'm moving?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_move) -- can I move an item from one drive to another without first downloading it?

[...I'm searching for?](http://graph.microsoft.io/docs/api-reference/v1.0/api/item_search)

[...I'm getting perms for?](http://graph.microsoft.io/docs/api-reference/v1.0/api/permission_get)

and basically the rest of what's in this list below...

<img width="159" alt="screen shot 2015-12-17 at 3 07 00 pm" src="https://cloud.githubusercontent.com/assets/990063/11884615/e0d38f4c-a4cf-11e5-9837-6ea09512baec.png">

**Comment by rgregg** [comment]
In Graph API right now, the only drive available for a user is the user's OneDrive for Business, which is at `/me/drive`. You can also access the drive for a Group by addressing the group and then the drive, like `/groups/{group-id}/drive`.

Basically, you can use `/drive` in the Graph API from anything that has a drive, which today is users and groups.

I'll see how we can update the docs for this to describe this better.

**Comment by keyur32** [comment]
Closing this for now.
