### ISSUE TITLE
Drives endpoint returns errors

### ISSUE THREAD

**Issue by Mike-Bell** [OfficeDev/microsoft-graph-docs#91]
I can obtain my drive information via `https://graph.microsoft.com/v1.0/me/drive`. If I turn around and call `https://graph.microsoft.com/v1.0/drives/<drive_id>` using the ID I just obtained, I get

```
Error: 500 - Internal Server Error
 See Response Headers for details.
{
  "error": {
    "code": "InternalServerError",
    "message": "Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JObject'.",
    "innerError": {
      "request-id": "3f359e3b-d187-4d76-9256-1a22a38eda05",
      "date": "2015-12-21T19:12:18"
    }
  }
}
```

`https://graph.microsoft.com/v1.0/drives` also returns this error (though I'm not sure if that call should work - it's not documented).

**Comment by rgregg** [comment]
I wasn't able to reproduce this behavior. To make sure I have the right repo, can you confirm this is what you're doing:

1. Make a request to GET https://graph.microsoft.com/v1.0/me/drive and receive drive properties, including a drive ID (looks something like `b!t18F8ybsHUq1...`.
2. Take this drive ID and feed it back into a request to GET https://graph.microsoft.com/v1.0/drives/{drive-id}.
3. Receive internal server error.

Assuming this is the repo, can you send me your tenant name so I can take a look at what's going on?

**Comment by Mike-Bell** [comment]
@rgregg yea those are indeed my repro steps. For good measure, I tried it with another user's drive that I know I can access via users/id/drive. The tenant I'm using for this is tscdev.

**Comment by rgregg** [comment]
Thanks Mike. Looking into this, it appears as though there's an authentication issue. Is the drive-id you are trying to access in the same tenant as the logged in user? Would it be possible for you to capture a fiddler trace of the whole repo and send it to me?

**Comment by Mike-Bell** [comment]
@rgregg I captured the relevant 2 calls. Capturing the auth steps is somewhat non-trivial since I'm relying on adal.js, but the trace does of course contain my access token which you can decode and inspect. However, I feel like pasting all this on a public forum is probably not appropriate, and my brief googling of you didn't reveal an email address. Do you have some channel via which I can deliver this info? I'm m.bell@techsmith.com

**Comment by rgregg** [comment]
I sent you an e-mail. If you want feel free to update your comment and remove your e-mail address now.

**Comment by narsenault** [comment]
I'm experiencing the same issue, has any progress been made with this?

**Comment by rgregg** [comment]
@narsenault Can you post the error message you're seeing please?

**Comment by narsenault** [comment]
@rgregg I'm using https://graphexplorer2.azurewebsites.net
GET request to https://graph.microsoft.com/v1.0/drive

Response:
{
    "error": {
        "code": "InternalServerError",
        "message": "Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JObject'.",
        "innerError": {
            "request-id": "c5a04dbd-ee08-4e03-b962-d96b0264604e",
            "date": "2016-01-28T18:22:00"
        }
    }
}

**Comment by rgregg** [comment]
That may be expected because you didn't include a user context. To get to a user's OneDrive, you need to include the user in the path:

`GET https://graph.microsoft.com/v1.0/me/drive`
or 
`GET https://graph.microsoft.com/v1.0/users/{upn}/drive`

**Comment by narsenault** [comment]
@rgregg Gotcha, okay. Bit of a misleading error message. Thanks for the assistance

**Comment by ErezSha** [comment]
I'm having a bit different issue.
I'm also getting an Internal Server Error, but a different one:
```json
{
   "error": {
     "code": "InternalServerError",
     "message": "Unable to resolve template token",
     "innerError": {
       "date": "2016-01-31T10:16:58",
       "request-id": "3fc7e678-2125-4740-add1-4a566ac0838f"
     }
   }
}
```
The endpoint I'm trying is: `https://graph.microsoft.com/v1.0/users/{user_id}/drive`
(I know the user_id is correct and the token is fine because `https://graph.microsoft.com/v1.0/users/{user_id}/manager` works).

**Comment by Mike-Bell** [comment]
@ErezSha Interesting. I'm able to to use `users/id/drive`. It's my current workaround for not being able to do `drives/id`

**Comment by Mike-Bell** [comment]
@rgregg FWIW, I checked on this again, and at some point I started getting a new error:

```

{
    "error": {
        "code": "UnknownError",
        "message": "{\"error\":\"invalid_client\",\"error_description\":\"Invalid audience Uri 'https:\\/\\/o365.sharepoint.com\\/'.\"}",
        "innerError": {
            "request-id": "af6862cf-9a25-4734-91db-fd92d2099371",
            "date": "2016-02-08T18:15:47"
        }
    }
}
```

To take a stab in the dark, I'd guess there's some string parsing error in the API. My user name is m.bell@o365.tsc-dev.co. It's coming back with `Invalid audience Uri 'https://o365.sharepoint.com/'.` whereas I'm pretty sure it wants `tscdev.sharepoint.com`.

**Comment by marych** [comment]
@Mike-Bell We've changed the Sharepoint endpoint discovery mechanism. Could you retry your request for the o365.tsc-dev.co tenant?

**Comment by Mike-Bell** [comment]
@marych seems like my repro is working now. Thanks! Gonna close this out.

**Comment by erangaapp** [comment]
I am trying to **https://graph.microsoft.com/v1.0/me/drive**. This one returns 

> {"_body":"{\r\n  \"error\": {\r\n    \"code\": \"InternalServerError\",\r\n    \"message\": \"Unable to resolve template token\",\r\n    \"innerError\": {\r\n      \"request-id\": \"97eb4ece-5a56-4de6-912c-79a006bb9f8b\",\r\n      \"date\": \"2017-05-26T11:18:16\"\r\n    }\r\n  }\r\n}","status":500,"ok":false,"statusText":"Internal Server Error","headers":{"client-request-id":["97eb4ece-5a56-4de6-912c-79a006bb9f8b"],"Content-Type":["application/json"],"Cache-Control":["private"],"request-id":["97eb4ece-5a56-4de6-912c-79a006bb9f8b"]},"type":2,"url":"https://graph.microsoft.com/v1.0/me/drive"}

but it work fine with **https://graph.microsoft.com/v1.0/me** It gives me to user account data. What's wrong with above request.
