### ISSUE TITLE
/manager endpoint returns Forbidden

### ISSUE THREAD

**Issue by ErezSha** [OfficeDev/microsoft-graph-docs#94]
When I send a GET to https://graph.microsoft.com/v1.0/users/<user_id>/manager,
 I get an error Forbidden (403).
error: {
  code: Authorization_RequestDenied,
  message:"Insufficient privileges to complete the operation",
  request-id:"06bbc4f9-8100-444d-b203-cbbb83ceb216"
}

I checked the scopes of the token I send with the request and it answers the scopes prerequisites of this endpoint.

What else could be the problem?

**Comment by martellaj** [comment]
Hey, @ErezSha. I wasn't able to repro this issue. Can you give me a little more info? What permissions do you have set for your app specifically?

**Comment by marych** [comment]
I checked in the logs that the permissions/scopes were: Device.ReadWrite.All, Group.Read.All, Directory.Read.All, User.Read.All.

**Comment by marych** [comment]
Also note that this is app-only auth flow.

**Comment by dkershaw10** [comment]
@ErezSha Can you try this again please? It looks like we had a regression.  This*should* be fixed now.

**Comment by ErezSha** [comment]
@dkershaw10 It's working now. Thanks.

**Comment by pethuraj143** [comment]
@dkershaw10   I am getting 403 Forbidden while hitting the below url obtained from 
@microsoft.graph.downloadUrl

https://developertcs.sharepoint.com/sites/test/_layouts/15/download.aspx?UniqueId=528531ac-15ac-4add-976a-056b2a16cb8e&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvZGV2ZWxvcGVydGNzLnNoYXJlcG9pbnQuY29tQDA1NGFjNzE4LWNhZDUtNDFjMC1iYWJkLTEyMWM4NTdkMTNhNCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE1MjM3MDQxNzYiLCJleHAiOiIxNTIzNzA3Nzc2IiwiZW5kcG9pbnR1cmwiOiJxY2dDRXVOTmo2VytoTkoxZG5JdGErVzVURGFEVXBLSnJZM09lS2pQcVdjPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTM0IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJZV000WlRVelpETXROMll5TUMwME16WTJMV0ZsWm1FdE5XUmpOamc1TVdaa056UTMiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWlRGaVpUZzNZVEF0WVRJd05TMDBNemxpTFRnM05EVXRabVl6WXpKaE16VmtZakl4IiwiYXBwX2Rpc3BsYXluYW1lIjoiTmV3QXBwIiwibmFtZWlkIjoiYzljZDY3YzgtZTVhNy00OWM2LThmMTAtODA3YTA1NTNlY2VhQDA1NGFjNzE4LWNhZDUtNDFjMC1iYWJkLTEyMWM4NTdkMTNhNCIsInJvbGVzIjoiYWxsc2l0ZXMucmVhZCBhbGxmaWxlcy5yZWFkIiwidHQiOiIxIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.YzYzdDNrS2ZhRDlHcUFoaUhHdEdCY0tPVVBHY09RbllpMVd2M1NNcU50ST0&ApiVersion=2.0

Is the regression or update is going on still.. kindly replay as soon as possible.
