### ISSUE TITLE
$expand unexpected behavior

### ISSUE THREAD

**Issue by ErezSha** [OfficeDev/microsoft-graph-docs#96]
Trying this: graph.microsoft.com/**beta**/users?$expand=manager,memberOf
returns 400:
{
  code:"BadRequest",
  message: The result of parsing $expand contained at least 2 items, but the maximum allowed is 1.
}
According to the docs: (http://graph.microsoft.io/docs/overview/query_parameters)
$expand: Comma-separated list of relationships to expand and include in the response.

Also,
Trying this: graph.microsoft.com/**v1.0**/users?$expand=manager,memberOf
returns the same error.

What should I expect from $expand?

**Comment by garethj-msft** [comment]
We have a fix in the works to remove this limitation.  At first you may see it replaced with a limit of two, and then shortly thereafter, removed entirely.

**Comment by marych** [comment]
@garethj-msft - the change you mentioned is already deployed and there is no longer a global limit for the number of expanded navigations. However, specific entities may still have limits and for users it is still limited to a single expanded navigation. That is not expected to change.

**Comment by angelgolfer-ms** [comment]
@ErezSha , FYI I updated the query parameters topic to clarify the limits on expanding a collection. The [query_parameters.md file](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/content/overview/query_parameters.md) in the repo already shows the updated content. The [topic](http://graph.microsoft.io/en-us/docs/overview/query_parameters) on the Microsoft Graph site will follow soon.
